"""
AURELIS Ludic Engine — reference Python implementation.
Mirrors the JS engine bit-for-bit on outputs.
"""

from __future__ import annotations
from typing import List


def ludic(n: int) -> List[int]:
    """
    Return all ludic numbers less than or equal to n.

    The ludic sequence is generated by a sieve analogous to the
    Sieve of Eratosthenes, but the removal stride is set by the
    survivor itself rather than by primality.

    >>> ludic(26)
    [1, 2, 3, 5, 7, 11, 13, 17, 23, 25]
    """
    try:
        limit = int(n)
    except (TypeError, ValueError):
        return []

    if limit < 1:
        return []

    result: List[int] = [1]
    if limit == 1:
        return result

    cap = max(limit * 20, 128)
    working = list(range(2, cap + 1))

    while working:
        stride = working[0]
        if stride > limit:
            break
        result.append(stride)
        working = [v for i, v in enumerate(working) if i % stride != 0]

    return [v for v in result if v <= limit]


def ludic_stream(k: int):
    """Yield the first k ludic numbers lazily."""
    if k <= 0:
        return
    yield 1
    if k == 1:
        return

    working = list(range(2, max(k * 20, 128)))
    emitted = 1
    while working and emitted < k:
        stride = working[0]
        yield stride
        emitted += 1
        working = [v for i, v in enumerate(working) if i % stride != 0]


if __name__ == "__main__":
    cases = {
        2: [1, 2],
        3: [1, 2, 3],
        5: [1, 2, 3, 5],
        20: [1, 2, 3, 5, 7, 11, 13, 17],
        26: [1, 2, 3, 5, 7, 11, 13, 17, 23, 25],
    }
    for n, expected in cases.items():
        got = ludic(n)
        status = "OK " if got == expected else "FAIL"
        print(f"[{status}] ludic({n}) = {got}")
